### ISSUE TITLE
Parser not working, am I using the right link format?

### ISSUE THREAD

**Issue by JeliHacker** [rsljr/python-edgar#4]
What is the correct format for links for to parse forms 3, 4, and 5? I tried using `https://www.sec.gov/Archives/edgar/data/103379/000112760224019866/xslF345X05/form4.xml` but I get errors, such as 
```
File "~/parse345_backup.py", line 47, in get_identity
    if issuer.find("issuerCik") is not None:
       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by rsljr** [comment]
It is not the correct link. As mentioned in the script: "You need to feed an SEC txt link into it." The txt version of your link is the following: https://www.sec.gov/Archives/edgar/data/103379/000112760224019866/0001127602-24-019866.txt

Also, the SEC no longer accepts anonymous/generic requests. You must update the header in the request with your information. See https://www.sec.gov/about/webmaster-frequently-asked-questions#code-support.
